import assert from 'node:assert/strict';
import { randomBytes, randomUUID, createHash } from 'node:crypto';
import nextEnv from '@next/env';
import mongoose from 'mongoose';
nextEnv.loadEnvConfig(process.cwd());
const base = process.env.AUTH_TEST_URL || 'http://localhost:3000';
const bypassHeaders = process.env.AUTH_TEST_BYPASS ? { 'x-vercel-protection-bypass': process.env.AUTH_TEST_BYPASS } : {};
const scope = `auth-test-${randomUUID()}`;
const ownerEmail = `${scope}@example.test`;
const memberEmail = `member-${scope}@example.test`;
const password = randomBytes(24).toString('base64url');
const newPassword = randomBytes(24).toString('base64url');
const enabledPassword = randomBytes(24).toString('base64url');
const invitation = randomBytes(32).toString('base64url');
const hash = value => createHash('sha256').update(value).digest('hex');
let db;
const cookies = response => response.headers.getSetCookie().map(value => value.split(';')[0]).join('; ');
async function api(path, body, cookie = '', origin = base) {
  const response = await fetch(`${base}${path}`, { method: body === undefined ? 'GET' : 'POST', redirect: 'manual', headers: { ...bypassHeaders, ...(body === undefined ? {} : { 'Content-Type': 'application/json', Origin: origin }), ...(cookie ? { Cookie: cookie } : {}) }, body: body === undefined ? undefined : JSON.stringify(body) });
  return response;
}
try {
  await mongoose.connect(process.env.MONGODB_URI, { dbName: process.env.MONGODB_DB || 'manage_from', serverSelectionTimeoutMS: 10000 });
  db = mongoose.connection.db;
  const mainBefore = await db.collection('workspaces').findOne({ _id: 'main' });
  await db.collection('workspace_invites').insertOne({ _id: hash(invitation), workspaceId: scope, role: 'owner', email: ownerEmail, expiresAt: new Date(Date.now() + 600000), createdAt: new Date(), createdBy: scope });
  assert.equal((await api('/api/workspace')).status, 401);
  assert.equal((await api('/api/workspace', { revision: 0, action: { type: 'invalid' } })).status, 401);
  const page = await fetch(base, { redirect: 'manual', headers: bypassHeaders });
  assert.equal(page.status, 307); assert.ok(page.headers.get('location').includes('/login'));
  assert.equal((await api('/api/auth/sign-up/email', { email: ownerEmail, password, name: 'Test owner' })).status, 403);
  assert.equal((await api('/api/auth/sign-in/email', { email: ownerEmail, password }, '', 'https://untrusted.example')).status, 403);
  assert.equal((await api('/api/access/accept', { token: invitation, email: memberEmail, password, name: 'Wrong email' })).status, 409);
  const accepted = await api('/api/access/accept', { token: invitation, email: ownerEmail, password, name: 'Auth test owner' });
  if (!accepted.ok) throw new Error(`Account acceptance failed: ${accepted.status} ${(await accepted.json()).message}`);
  assert.deepEqual(await accepted.clone().json(), { success: true });
  assert.ok(accepted.headers.getSetCookie().some(value => /HttpOnly/i.test(value) && /SameSite=Lax/i.test(value)));
  if (base.startsWith('https:')) assert.ok(accepted.headers.getSetCookie().some(value => /Secure/i.test(value)));
  let ownerCookie = cookies(accepted);
  assert.ok(ownerCookie.includes('manage-from.session_token='));
  assert.equal((await api('/api/access/accept', { token: invitation, email: ownerEmail, password, name: 'Auth test owner' })).status, 410);
  const ownerSession = await (await api('/api/auth/get-session', undefined, ownerCookie)).json();
  assert.equal(ownerSession.user.email, ownerEmail);
  const storedAccount = await db.collection('auth_accounts').findOne({ userId: new mongoose.Types.ObjectId(ownerSession.user.id) });
  assert.ok(storedAccount.password && storedAccount.password !== password);
  await db.collection('workspace_members').updateOne({ _id: ownerSession.user.id, workspaceId: scope }, { $set: { mustChangePassword: true } });
  const blocked = await api('/api/workspace', undefined, ownerCookie);
  assert.equal(blocked.status, 403); assert.equal((await blocked.json()).error.code, 'PASSWORD_CHANGE_REQUIRED');
  assert.equal((await api('/api/workspace', { revision: 0, action: { type: 'invalid' } }, ownerCookie)).status, 403);
  const setupPage = await fetch(base, { redirect: 'manual', headers: { ...bypassHeaders, Cookie: ownerCookie } });
  assert.equal(setupPage.status, 307); assert.ok(setupPage.headers.get('location').includes('/account'));
  assert.equal((await api('/api/access/team', { email: memberEmail, name: 'Test member', password }, ownerCookie)).status, 403);
  assert.equal((await api('/api/auth/admin/create-user', { email: memberEmail, password, name: 'Test member' }, ownerCookie)).status, 403);
  assert.equal((await api('/api/auth/change-password', { currentPassword: password, newPassword: password }, ownerCookie)).status, 400);
  assert.equal((await api('/api/auth/change-password', { currentPassword: 'incorrect-password', newPassword: enabledPassword }, ownerCookie)).status, 400);
  const enabled = await api('/api/auth/change-password', { currentPassword: password, newPassword: enabledPassword, revokeOtherSessions: true }, ownerCookie);
  assert.equal(enabled.status, 200); ownerCookie = cookies(enabled) || ownerCookie;
  assert.equal((await api('/api/workspace', { revision: 0, action: { type: 'invalid' } }, ownerCookie)).status, 422);
  const write = await api('/api/workspace', { workspaceId: 'main', revision: 0, action: { type: 'add-creditor', creditor: { id: scope, name: 'Auth fixture', description: '', color: 'cyan', favorite: false } } }, ownerCookie);
  assert.equal(write.status, 200);
  const saved = await (await api('/api/workspace', undefined, ownerCookie)).json();
  assert.equal(saved.data.workspace.creditors[0].id, scope);
  assert.deepEqual(await db.collection('workspaces').findOne({ _id: 'main' }), mainBefore);
  const created = await api('/api/access/team', { email: memberEmail, name: 'Auth test member', password, role: 'owner', workspaceId: 'main' }, ownerCookie);
  assert.equal(created.status, 201);
  assert.equal(created.headers.getSetCookie().length, 0);
  const createdMember = (await created.json()).member;
  assert.equal(createdMember.role, 'member'); assert.equal(createdMember.mustChangePassword, true);
  assert.equal((await api('/api/access/team', { email: memberEmail, name: 'Duplicate', password }, ownerCookie)).status, 409);
  assert.equal((await (await api('/api/auth/get-session', undefined, ownerCookie)).json()).user.id, ownerSession.user.id);
  const memberResponse = await api('/api/auth/sign-in/email', { email: memberEmail, password });
  assert.equal(memberResponse.status, 200);
  let memberCookie = cookies(memberResponse);
  assert.equal((await api('/api/workspace', undefined, memberCookie)).status, 403);
  const memberChanged = await api('/api/auth/change-password', { currentPassword: password, newPassword: newPassword, revokeOtherSessions: true }, memberCookie);
  assert.equal(memberChanged.status, 200); memberCookie = cookies(memberChanged) || memberCookie;
  assert.equal((await api('/api/access/team', { email: 'outside@example.test' }, memberCookie)).status, 403);
  assert.equal((await api('/api/workspace', undefined, memberCookie)).status, 200);
  const member = await db.collection('workspace_members').findOne({ email: memberEmail, workspaceId: scope });
  await db.collection('workspace_members').deleteOne({ _id: member._id, workspaceId: scope });
  assert.equal((await api('/api/workspace', undefined, memberCookie)).status, 401);
  const tampered = ownerCookie.replace(/session_token=./, 'session_token=X');
  assert.equal((await api('/api/workspace', undefined, tampered)).status, 401);
  assert.equal((await api('/api/auth/sign-in/email', { email: ownerEmail, password: 'wrong-password' })).status, 401);
  const login = await api('/api/auth/sign-in/email', { email: ownerEmail, password: enabledPassword });
  assert.equal(login.status, 200);
  const secondCookie = cookies(login);
  const changed = await api('/api/auth/change-password', { currentPassword: enabledPassword, newPassword, revokeOtherSessions: true }, ownerCookie);
  assert.equal(changed.status, 200);
  assert.equal((await api('/api/workspace', undefined, secondCookie)).status, 401);
  assert.equal((await api('/api/auth/sign-in/email', { email: ownerEmail, password })).status, 401);
  const relogin = await api('/api/auth/sign-in/email', { email: ownerEmail, password: newPassword });
  assert.equal(relogin.status, 200);
  const finalCookie = cookies(relogin);
  assert.equal((await api('/api/auth/sign-out', {}, finalCookie)).status, 200);
  assert.equal((await api('/api/workspace', undefined, finalCookie)).status, 401);
  assert.equal((await api('/api/auth/sign-in/email', { email: ownerEmail, password: newPassword })).status, 429);
  console.log('Auth passed: guards, blocked public admin endpoints, first-login password gates, password reuse rejection, admin-created users, role/workspace injection protection, preserved admin session, duplicate prevention, hashing, logout and rate limits.');
} catch (error) {
  console.error(`Auth check failed: ${error.message}. Credentials omitted.`);
  process.exitCode = 1;
} finally {
  if (db) {
    const users = await db.collection('auth_users').find({ email: { $in: [ownerEmail, memberEmail] } }).toArray();
    const ids = users.map(user => user._id);
    const strings = ids.map(id => String(id));
    await db.collection('auth_sessions').deleteMany({ userId: { $in: ids } });
    await db.collection('auth_accounts').deleteMany({ userId: { $in: ids } });
    await db.collection('auth_users').deleteMany({ _id: { $in: ids } });
    await db.collection('workspace_members').deleteMany({ _id: { $in: strings }, workspaceId: scope });
    await db.collection('workspace_invites').deleteMany({ workspaceId: scope });
    await db.collection('workspaces').deleteOne({ _id: scope });
    console.log('Only accounts and records created by this auth check were removed.');
  }
  await mongoose.disconnect();
}
